### ISSUE TITLE
example fetch-website

### ISSUE THREAD

**Issue by fxguillois** [Richard-W/curl-vala#3]
Hi,

i've tried the fetch-website.vala example. The result have numerous errors into it : 
[fetch-website.txt](https://github.com/Richard-W/curl-vala/files/59845/fetch-website.txt)

I don't know if it's a standard ouput, but it frightens me. ;)

Thanks,

**Comment by Richard-W** [comment]
The txt file you posted is an executable which i will not execute. Sorry. I'll look into the examples though.

**Comment by richard-w** [comment]
Example works fine for me. You might have to adjust PKG_CONFIG_PATH when you installed the library to /usr/local.

**Comment by Richard-W** [comment]
Example works fine for me. You might have to adjust PKG_CONFIG_PATH when you installed the library to /usr/local.
